[start]
command:/usr/local/etc/rc.d/mosdns start
parameters:
type:script
message:starting MosDNS

[stop]
command:/usr/local/etc/rc.d/mosdns stop
parameters:
type:script
message:stopping MosDNS

[restart]
command:/usr/local/etc/rc.d/mosdns restart
parameters:
type:script
message:restarting MosDNS

[status]
command:/usr/local/etc/rc.d/mosdns status; exit 0
parameters:
type:script_output
message:request MosDNS status

[reload]
command:/usr/local/etc/rc.d/mosdns reload
parameters:
type:script
message:request MosDNS reload

[reconfigure]
command:/usr/local/opnsense/scripts/OPNsense/MosDNS/generate_config.sh && /usr/local/etc/rc.d/mosdns restart
parameters:
type:script
message:reconfiguring MosDNS

[log]
command:/usr/bin/tail -n 100 /var/log/mosdns.log 2>/dev/null || echo "MosDNS log file not found"
parameters:
type:script_output
message:request MosDNS log

[clearlog]
command:/usr/bin/truncate -s 0 /var/log/mosdns.log 2>/dev/null || echo "Log file not found"
parameters:
type:script
message:clearing MosDNS log