PLUGIN_NAME=		os-mosdns
PLUGIN_VERSION=		5.3.3
PLUGIN_COMMENT=		OPNsense MosDNS Plugin
PLUGIN_DEPENDS=		
PLUGIN_MAINTAINER=	opnsense@deciso.com
PLUGIN_WWW=		https://github.com/IrineSistiana/mosdns

.include "../../Mk/plugins.mk"