PLUGIN_NAME=		os-mosdns
PLUGIN_VERSION=		5.3.3
PLUGIN_COMMENT=		OPNsense MosDNS Plugin
PLUGIN_DEPENDS=		
PLUGIN_MAINTAINER=	opnsense@deciso.com
PLUGIN_WWW=		https://github.com/IrineSistiana/mosdns
PLUGIN_PHP=		8.3
PLUGIN_PYTHON=		3.12

.include "./Mk/plugins.mk"